[package]
name = "xwords"
version = "0.1.0"
authors = ["Sam Szuflita <sam.szuflita@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
bincode = "1.3.1"
lazy_static = "1.4.0"
cached = "0.19.0"

[dev-dependencies]
criterion = "0.3"
pprof = { version = "0.3", features = ["flamegraph"] } 

[[example]]
name = "sample"
path = "examples/sample.rs"